### Get projects
GET http://admin:admin@localhost:8111/app/rest/projects
Accept: application/json

### Get builds
GET http://admin:admin@localhost:8111/app/rest/builds
Accept: application/json

### Get VCS roots
GET http://admin:admin@localhost:8111/app/rest/vcs-roots
Accept: application/json

### Get build configurations
GET http://admin:admin@localhost:8111/app/rest/buildTypes
Accept: application/json

### Get build configurations
GET http://admin:admin@localhost:8111/app/rest/buildTypes
Accept: application/json

### Get build configuration
GET http://admin:admin@localhost:8111/app/rest/buildTypes/id:SpringCoreForQa_Build
Accept: application/json
